### ISSUE TITLE
LiPo Mezz

### ISSUE THREAD

**Issue by ric96** [mwelling/96boards-community#5]
Pretty self explanatory, a mezz that can charge a lipo and then use the lipo to supply power to the board like in any smartphone. With all the protection circuit etc.
Possibly the connector for charging the lipo being a standard micro usb at 5v
and then users can add their own 3v7 lipo pack to it.

**Comment by ukBaz** [comment]
For a mezzanine board I would propose using an Li-ion 18650 as they give good performance and can be secured to the board easier with [battery clips](https://www.arrow.com/en/products/82/keystone-electronics)

Some background reading for reference:
https://www.arrow.com/en/products/82/keystone-electronics

**Comment by mwelling** [comment]
Something similar to the following would be nice.
https://www.adafruit.com/product/2465

We would have to boost the output voltage a more but it is a good reference.

**Comment by mwelling** [comment]
Issue moved to new repository.
