### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by ukBaz** [mwelling/96boards-community#7]
Before you add any real content you should attach a license to ensure things can be shared and used as intended as without a license, the default copyright laws apply, meaning that you retain all rights to your this project and no one may reproduce, distribute, or create derivative works from your work. As this your intent is creating an open source project, it would seem sensible to include an open source license.

**Comment by mwelling** [comment]
Yes, I remember bring this up in the meeting.

Here are licenses that I have used:
https://creativecommons.org/licenses/by-sa/4.0/
http://www.ohwr.org/attachments/2388/cern_ohl_v_1_2.txt

Here is a more LGPL like license for hardware if you think it might be better:
https://creativecommons.org/licenses/by/4.0/

**Comment by mwelling** [comment]
The template released by Linaro is licensed using a BSD license:
https://github.com/96boards/96boards-kicad-mezzanine-template/blob/master/COPYING

If we try to pull in this template we need to consider that.

**Comment by mwelling** [comment]
Issue moved to new repository.
